### ISSUE TITLE
version of dotnet core cli used.

### ISSUE THREAD

**Issue by kktam** [telerik/kendo-angular-quickstart-dotnet#5]
As of July 2019, the stable release for dotnet core is 2.2.3. However the template generated by dotnet core 2.2.3 only uses Angular 6.  Checking from this example the Angular used is Angular 7. Please indicate the version of dotnet core used to generate this template, and provide the dotnet core and cli version and the link to install it, in order for sample users to match the environment settings.

**Comment by tsvetomir** [comment]
The project is generated with dotnet core 2.2.x, but the client application was updated separately in e220cd4a9e280d67903637678b8425086bdd3ba4.

**Comment by kktam** [comment]
Thanks. Question solved.
